# Generated by Django 3.1.3 on 2020-11-26 14:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcoMart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='address',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contact',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='reference',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
