# Generated by Django 3.1.3 on 2020-11-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digital_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
