# Generated by Django 3.1.3 on 2020-11-26 13:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_product_digital_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
